### ISSUE TITLE
Should we include federated EMNIST dataset?

### ISSUE THREAD

**Issue by rbnuria** [sherpaai/Sherpa.ai-Federated-Learning-Framework#178]
I think we should include the functionality of loading federated EMNIST dataset like in https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data?hl=es-419.

The EMNIST dataset is, by nature, federated as it has been created collecting numbers of different writers. In some papers, they use this configuration for experimentation so, if we can to make our framework capable of reproducing these experiments, we should add this functionality.

**Comment by gegose** [comment]
Yes, this kind of dataset sounds very interesting to me.

**Comment by rbnuria** [comment]
Fine, I'll study the adaptation of this kind of dataset to Sherpa.FL.
