### ISSUE TITLE
No-iid distribution loses data

### ISSUE THREAD

**Issue by josebummer** [sherpaai/Sherpa.ai-Federated-Learning-Framework#179]
Hi,

In file [shfl/data_distribution/data_distribution_non_iid.py](https://github.com/sherpaai/Sherpa.ai-Federated-Learning-Framework/blob/master/shfl/data_distribution/data_distribution_non_iid.py), when we choose no-iid data distribution without replacement, the code is as follows:

```python
112           for i in range(0, num_nodes):
113                labels_to_use = random_classes[i]
114
115                idx = np.array([True if i in labels_to_use else False for i in labels.argmax(axis=-1)])
116                data_aux = data[idx]
117                rest_data = data[~idx]
118                labels_aux = labels[idx]
119                rest_labels = labels[~idx]
120
121                randomize = np.arange(len(labels_aux))
122                np.random.shuffle(randomize)
123                data_aux = data_aux[randomize, ]
124                labels_aux = labels_aux[randomize]
125
126                percent_per_client = min(int(weights[i] * len(data)), len(data_aux))
127
128                federated_data.append(np.array(data_aux[0:percent_per_client, ]))
129                rest_data = np.append(rest_data, data_aux[percent_per_client:, ], axis=0)
130                federated_label.append(np.array(labels_aux[0:percent_per_client, ]))
131                rest_labels = np.append(rest_labels, labels_aux[percent_per_client:, ], axis=0)
132
133                data = rest_data
134                labels = rest_labels
```

In line 126 we calc percent per client using `len(data)`, but in line 133, we change `data`. So, in the next iteration, `len(data)` will be different that iteration before, and `weights[i+1] * len(data)` will be wrong. 

For example, with `weights = [0.5, 0.5]` and `data` with 1000 elements, in the first iteration `weights[0] * len(data) = 500`, but in the second iteration `len(data) = 500` because `data` was changed in line 133, so `weights[1] * len(data) = 250` and `weights[1] * len(data)` should be 500.

I think that this is a bug but I have put the question label for know your opinion. If you are agree with me, I will change it.

Regards.

**Comment by rbnuria** [comment]
Yes! I think you're right. Maybe you could calculate a vector of percent_per_client before entering the loop.

Go for it! ;)
