### ISSUE TITLE
Add some state of the art federated aggregators

### ISSUE THREAD

**Issue by xehartnort** [sherpaai/Sherpa.ai-Federated-Learning-Framework#183]
Particularly, the norm clipping aggregator, which clips the norm of the weights of each client before aggregating, and the weak differential privacy aggregator, which does clips the norm in the same fashion and adds gaussian noise with std=0.025

**Comment by gegose** [comment]
Missing coverage:
shfl/federated_aggregator/norm_clip_aggregators.py            47      1    98%

**Comment by xehartnort** [comment]
Thank you for noticing, I have opened a new PR which fixes the missing 2% coverage 👍
